### ISSUE TITLE
Pretrain Model

### ISSUE THREAD

**Issue by Ahnsun** [megvii-model/MOTR#1]
Could you please provide the version of pretrain model. I downloaded the r50_deformable_detr-checkpoint.pth but the there is an error in loading state_dict for MOTR

**Comment by dbofseuofhust** [comment]
> Could you please provide the version of pretrain model. I downloaded the r50_deformable_detr-checkpoint.pth but the there is an error in loading state_dict for MOTR

hi~, we use Deformable DETR, r50 + iterative bounding box refinement, you should download this model: https://drive.google.com/file/d/1JYKyRYzUH7uo9eVfDaVCiaIGZb5YTCuI/view

**Comment by zzzz94** [comment]
> > Could you please provide the version of pretrain model. I downloaded the r50_deformable_detr-checkpoint.pth but the there is an error in loading state_dict for MOTR
> 
> hi~, we use Deformable DETR, r50 + iterative bounding box refinement, you should download this model: https://drive.google.com/file/d/1JYKyRYzUH7uo9eVfDaVCiaIGZb5YTCuI/view

hello, I have tried the pretrained model above, but meet the error:

`RuntimeError: Error(s) in loading state_dict for MOTR:
        size mismatch for class_embed.0.weight: copying a param with shape torch.Size([91, 256]) from checkpoint, the shape in current model is torch.Size([1, 256]).`

After ignoring the model parameter size mismatch, I get another error about size mismatch of optimizer:
`ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`

How did you solve it? Could you give any suggestions?Thanks.

**Comment by dbofseuofhust** [comment]
> > > Could you please provide the version of pretrain model. I downloaded the r50_deformable_detr-checkpoint.pth but the there is an error in loading state_dict for MOTR
> > 
> > 
> > hi~, we use Deformable DETR, r50 + iterative bounding box refinement, you should download this model: https://drive.google.com/file/d/1JYKyRYzUH7uo9eVfDaVCiaIGZb5YTCuI/view
> 
> hello, I have tried the pretrained model above, but meet the error:
> 
> `RuntimeError: Error(s) in loading state_dict for MOTR: size mismatch for class_embed.0.weight: copying a param with shape torch.Size([91, 256]) from checkpoint, the shape in current model is torch.Size([1, 256]).`
> 
> After ignoring the model parameter size mismatch, I get another error about size mismatch of optimizer:
> `ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`
> 
> How did you solve it? Could you give any suggestions?Thanks.

Did you modify any codes? or could you paste the .sh command here?

**Comment by zzzz94** [comment]
> > > > Could you please provide the version of pretrain model. I downloaded the r50_deformable_detr-checkpoint.pth but the there is an error in loading state_dict for MOTR
> > > 
> > > 
> > > hi~, we use Deformable DETR, r50 + iterative bounding box refinement, you should download this model: https://drive.google.com/file/d/1JYKyRYzUH7uo9eVfDaVCiaIGZb5YTCuI/view
> > 
> > 
> > hello, I have tried the pretrained model above, but meet the error:
> > `RuntimeError: Error(s) in loading state_dict for MOTR: size mismatch for class_embed.0.weight: copying a param with shape torch.Size([91, 256]) from checkpoint, the shape in current model is torch.Size([1, 256]).`
> > After ignoring the model parameter size mismatch, I get another error about size mismatch of optimizer:
> > `ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`
> > How did you solve it? Could you give any suggestions?Thanks.
> 
> Did you modify any codes? or could you paste the .sh command here?

PRETRAIN in r50_motr_train.sh is set to r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth(the link you provided above) because I don't find coco_model_final.pth.

**Comment by TerranLord** [comment]
@dbofseuofhust @zzzz94 This error may cause by the '--resume {PRETRAIN}' in the training script.  Just remove that.

**Comment by zzzz94** [comment]
> @dbofseuofhust @zzzz94 This error may cause by the '--resume {PRETRAIN}' in the training script. Just remove that.

thx, I'll try it.

**Comment by eeric** [comment]
> > > Could you please provide the version of pretrain model. I downloaded the r50_deformable_detr-checkpoint.pth but the there is an error in loading state_dict for MOTR
> > 
> > 
> > hi~, we use Deformable DETR, r50 + iterative bounding box refinement, you should download this model: https://drive.google.com/file/d/1JYKyRYzUH7uo9eVfDaVCiaIGZb5YTCuI/view
> 
> hello, I have tried the pretrained model above, but meet the error:
> 
> `RuntimeError: Error(s) in loading state_dict for MOTR: size mismatch for class_embed.0.weight: copying a param with shape torch.Size([91, 256]) from checkpoint, the shape in current model is torch.Size([1, 256]).`
> 
> After ignoring the model parameter size mismatch, I get another error about size mismatch of optimizer:
> `ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`
> 
> How did you solve it? Could you give any suggestions?Thanks.

pytorch version is mismatch

**Comment by noahcao** [comment]
I am getting into the same problem:

![image](https://user-images.githubusercontent.com/17743251/139748539-3348190a-fba7-4787-aec3-ff7c3bfd6440.png)

All I did is uncommenting the command in configs/r50_motr_train.sh and replace $PRETRAIN with the checkpoint you suggested above (https://drive.google.com/file/d/1JYKyRYzUH7uo9eVfDaVCiaIGZb5YTCuI/view).

![image](https://user-images.githubusercontent.com/17743251/139748622-bd3d4128-0bb9-469a-895b-76065a9142ad.png)

@dbofseuofhust Do you have any idea about this? Anything to be updated in your README guidelines?
