### ISSUE TITLE
little bug using joint.train 

### ISSUE THREAD

**Issue by eeric** [megvii-model/MOTR#10]
in datasets/joint.py
the line 101,102:
        if 'crowdhuman' in img_path:
            img_path = img_path.replace('.jpg', '.png')

that should be remove, because crowdhuman format is .jpg.

**Comment by dbofseuofhust** [comment]
> in datasets/joint.py
> the line 101,102:
> if 'crowdhuman' in img_path:
> img_path = img_path.replace('.jpg', '.png')
> 
> that should be remove, because crowdhuman format is .jpg.

Thanks for your fix, we will update this.
