### ISSUE TITLE
About "calc_loss_for_track_scores"

### ISSUE THREAD

**Issue by BritaryZhou** [megvii-model/MOTR#11]
Hi~ 

Thank you for providing such an interesting work!
I just have some questions about the "calc_loss_for_track_scores" part. In the project, there is another “track_cls” branch in the memory bank, which is not mentioned in the paper. I am wondering what's the function of this branch and how important this corresponding loss ("calc_loss_for_track_scores") is. 

Looking forward to your kindly reply. Thanks a lot~

**Comment by vaesl** [comment]
> Hi~
> 
> Thank you for providing such an interesting work!
> I just have some questions about the "calc_loss_for_track_scores" part. In the project, there is another “track_cls” branch in the memory bank, which is not mentioned in the paper. I am wondering what's the function of this branch and how important this corresponding loss ("calc_loss_for_track_scores") is.
> 
> Looking forward to your kindly reply. Thanks a lot~

Thanks for your attention on MOTR! Previously, we planed to employ the loss "calc_loss_for_track_scores"  to enhance the existence of tracked objects in history. It will not affect the overall performance through ablation experiments, so we do not write its description in our paper. You can simply remove this branch if you plan to rerun the MOTR code.
