### ISSUE TITLE
About empty query set

### ISSUE THREAD

**Issue by wzic** [megvii-model/MOTR#12]
Hi!

I have some questions regarding the empty query set:
(1) What is the definition of the empty query set? It seems that the definition of this concept is not mentioned in the paper.
(2) How many queries does the empty query set contain? Why is it call "empty" ?
(3) Does the empty query set have a similar function to the 300 object queries in TrackFormer ?

Thank you.

**Comment by dbofseuofhust** [comment]
> Hi!
> 
> I have some questions regarding the empty query set:
> (1) What is the definition of the empty query set? It seems that the definition of this concept is not mentioned in the paper.
> (2) How many queries does the empty query set contain? Why is it call "empty" ?
> (3) Does the empty query set have a similar function to the 300 object queries in TrackFormer ?
> 
> Thank you.

Thanks for attention!
(1) and (3):
     we treat the case that new object entrance as a object detection process; the defination of empty query is not completely 
    same as that in TrackFormer; empty query  contains two parts: initial object query (300,default), track query that object exited 
   (the object disappear and last frame's track query can also raise response to new object); 
(2) the 'empty' is relative to track query, because they are responable for objects that appear first time.
