### ISSUE TITLE
Reference points for MOTR, possible BUG

### ISSUE THREAD

**Issue by RQuispeC** [megvii-model/MOTR#14]
I have a question about line 538 in [motr](https://github.com/megvii-model/MOTR/blob/main/models/motr.py)

```
ref_pts_all = torch.cat([init_reference[None], inter_references[:, :, :, :2]], dim=0)
out = {'pred_logits': outputs_class[-1], 'pred_boxes': outputs_coord[-1], 'ref_pts': ref_pts_all[5]}
```

Considering the transformer has 6 layers in the decoder, `ref_pts_all[5]` corresponds to the reference points in the second to last layer. Shouldn't this be the last layer instead?

```
ref_pts_all = torch.cat([init_reference[None], inter_references[:, :, :, :2]], dim=0)
out = {'pred_logits': outputs_class[-1], 'pred_boxes': outputs_coord[-1], 'ref_pts': ref_pts_all[-1]}
```

**Comment by dbofseuofhust** [comment]
> I have a question about line 538 in [motr](https://github.com/megvii-model/MOTR/blob/main/models/motr.py)
> 
> ```
> ref_pts_all = torch.cat([init_reference[None], inter_references[:, :, :, :2]], dim=0)
> out = {'pred_logits': outputs_class[-1], 'pred_boxes': outputs_coord[-1], 'ref_pts': ref_pts_all[5]}
> ```
> 
> Considering the transformer has 6 layers in the decoder, `ref_pts_all[5]` corresponds to the reference points in the second to last layer. Shouldn't this be the last layer instead?
> 
> ```
> ref_pts_all = torch.cat([init_reference[None], inter_references[:, :, :, :2]], dim=0)
> out = {'pred_logits': outputs_class[-1], 'pred_boxes': outputs_coord[-1], 'ref_pts': ref_pts_all[-1]}
> ```

Thanks for attention!
Actually, the index of 'ref_pts_all' starts from 0 and ends with 5 for 6 layers in decoder.  Thus 'ref_pts_all[5]' is equal to 'ref_pts_all[-1]'.
