### ISSUE TITLE
No module named 'detectron2'

### ISSUE THREAD

**Issue by tdchua** [megvii-model/MOTR#15]
Hello! I followed all your instructions regarding the installation of MOTR, but I ran across this problem. The instructions did not mention the steps for detectron2, so I tried installing it from this website https://github.com/facebookresearch/detectron2/releases
However, it requires Torch version of at least 1.7

But in the instructions, pytorch = 1.5.1 
Have you encountered this problem and what is your workaround?

Thank you very much!

**Comment by louis979181873** [comment]
I have all counter this problem! I think it's dut to the demo is made on another envirnment. It's totally unimplementable to execute this script.
