### ISSUE TITLE
Demo video script 

### ISSUE THREAD

**Issue by ayanasser** [megvii-model/MOTR#16]
Hello, 
Thank you for your great work, 
am asking for a script for testing my own video with your pretrained model 
Thank you ^^

**Comment by dbofseuofhust** [comment]
> Hello,
> Thank you for your great work,
> am asking for a script for testing my own video with your pretrained model
> Thank you ^^

Thanks for attention!
We provide visual script here https://github.com/megvii-model/MOTR/blob/main/eval.py.
For testing your own video, please kind modify these two lines (just replace the 'mot_path' into yours):
https://github.com/megvii-model/MOTR/blob/main/eval.py#L271
https://github.com/megvii-model/MOTR/blob/main/eval.py#L422
