### ISSUE TITLE
How to modify multi-class

### ISSUE THREAD

**Issue by xinghaizhu** [megvii-model/MOTR#19]

**Comment by dbofseuofhust** [comment]
> _No description provided._

Thanks for attention!
For multi-class you can just do little changes as follows:
1. Training:
    i) modify dataset https://github.com/megvii-model/MOTR/blob/main/datasets/joint.py#L138 as `num_classes`;
    ii) modify model https://github.com/megvii-model/MOTR/blob/main/models/motr.py#L622 as `num_classes`;
    other architure need no changes.
2. Inference:
    i) modify this line https://github.com/megvii-model/MOTR/blob/main/eval.py#L161 as `label  < num_classes`;

**Comment by xinghaizhu** [comment]
&nbsp; &nbsp; &nbsp; 师兄您好，请问数据集得标注也应该为<class，id，bbox&gt;么，还有我看论文及代码只也使用了crowdhuman进行训练，我修改得时候需要去除这段代码么，刚开始学习这方面不太懂。
&nbsp; &nbsp; &nbsp; 谢谢师兄




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-model/MOTR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-model/MOTR] How to modify multi-class (#19)





  
No description provided.
  
Thanks for attention!
 For multi-class you can just do little changes as follows:
  
Training:
 i) modify dataset https://github.com/megvii-model/MOTR/blob/main/datasets/joint.py#L138 as num_classes;
 ii) modify model https://github.com/megvii-model/MOTR/blob/main/models/motr.py#L622 as num_classes;
 other architure need no changes.
 
Inference:
 i) modify this line https://github.com/megvii-model/MOTR/blob/main/eval.py#L161 as label  < num_classes;
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xinghaizhu** [comment]
> > _未提供说明。_
> 
> 感谢大家的关注！
> 对于多类，您可以做以下小更改：
> 
> 1. 培训：i）修改数据集https://github.com/megvii-model/MOTR/blob/main/datasets/joint.py#L138为： ii） 修改模型https://github.com/megvii-model/MOTR/blob/main/models/motr.py#L622为：其他拱门不需要更改。`num_classes``num_classes`
> 2. 推论：i）修改此行https://github.com/megvii-model/MOTR/blob/main/eval.py#L161`label  < num_classes`;

Hello,should the gt be <class，id，bbox>? ，and the code use the CrowdHuman to train，Do I need to remove this code when I modify it?  Thank you very much!

**Comment by xinghaizhu** [comment]
> > _No description provided._
> 
> Thanks for attention!
> For multi-class you can just do little changes as follows:
> 
> 1. Training:
>    i) modify dataset https://github.com/megvii-model/MOTR/blob/main/datasets/joint.py#L138 as `num_classes`;
>    ii) modify model https://github.com/megvii-model/MOTR/blob/main/models/motr.py#L622 as `num_classes`;
>    other architure need no changes.
> 2. Inference:
>    i) modify this line https://github.com/megvii-model/MOTR/blob/main/eval.py#L161 as `label  < num_classes`;

Hello,should the gt be <class，id，bbox>? ，and the code use the CrowdHuman to train，Do I need to remove this code when I modify it? Thank you very much!
