### ISSUE TITLE
Offline vs Online

### ISSUE THREAD

**Issue by Fungungun** [megvii-model/MOTR#2]
Hi

Thanks for your work and it looks awesome. 

Just wondering if the proposed MOTR is offline MOT or online MOT ?

If it's offline tracking is it possible to convert it to online tracking ?

Thanks

**Comment by dbofseuofhust** [comment]
> Hi
> 
> Thanks for your work and it looks awesome.
> 
> Just wondering if the proposed MOTR is offline MOT or online MOT ?
> 
> If it's offline tracking is it possible to convert it to online tracking ?
> 
> Thanks

hi~, MOTR is online MOT.
