### ISSUE TITLE
demo with the problem of environment

### ISSUE THREAD

**Issue by Z-Yh-June** [megvii-model/MOTR#22]
when i run demo , i meet this problem :

(pytracking) ...~/zyh/MOTR$ sh configs/r50_motr_demo.sh
Traceback (most recent call last):
  File "./demo.py", line 28, in <module>
    from models import build_model
  File "/home/lx/zyh/MOTR/models/__init__.py", line 10, in <module>
    from .deformable_detr import build as build_deformable_detr
  File "/home/lx/zyh/MOTR/models/deformable_detr.py", line 29, in <module>
    from .deformable_transformer import build_deforamble_transformer
  File "/home/lx/zyh/MOTR/models/deformable_transformer.py", line 25, in <module>
    from models.ops.modules import MSDeformAttn
  File "/home/lx/zyh/MOTR/models/ops/modules/__init__.py", line 12, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/home/lx/zyh/MOTR/models/ops/modules/ms_deform_attn.py", line 24, in <module>
    from ..functions import MSDeformAttnFunction
  File "/home/lx/zyh/MOTR/models/ops/functions/__init__.py", line 12, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/lx/zyh/MOTR/models/ops/functions/ms_deform_attn_func.py", line 21, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/lx/anaconda3/envs/pytracking/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa

my environment as follow:
torch  version:1.5.1
torchvision  version :  0.6.0a0+35d732a
cuda : 9.2

The environmental problem has been bothering me for several days and has not been solved yet,if you have same problem,i really hope you can help me.Thank you !

**Comment by dbofseuofhust** [comment]
> when i run demo , i meet this problem :
> 
> (pytracking) ...~/zyh/MOTR$ sh configs/r50_motr_demo.sh Traceback (most recent call last): File "./demo.py", line 28, in from models import build_model File "/home/lx/zyh/MOTR/models/**init**.py", line 10, in from .deformable_detr import build as build_deformable_detr File "/home/lx/zyh/MOTR/models/deformable_detr.py", line 29, in from .deformable_transformer import build_deforamble_transformer File "/home/lx/zyh/MOTR/models/deformable_transformer.py", line 25, in from models.ops.modules import MSDeformAttn File "/home/lx/zyh/MOTR/models/ops/modules/**init**.py", line 12, in from .ms_deform_attn import MSDeformAttn File "/home/lx/zyh/MOTR/models/ops/modules/ms_deform_attn.py", line 24, in from ..functions import MSDeformAttnFunction File "/home/lx/zyh/MOTR/models/ops/functions/**init**.py", line 12, in from .ms_deform_attn_func import MSDeformAttnFunction File "/home/lx/zyh/MOTR/models/ops/functions/ms_deform_attn_func.py", line 21, in import MultiScaleDeformableAttention as MSDA ImportError: /home/lx/anaconda3/envs/pytracking/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa
> 
> my environment as follow: torch version:1.5.1 torchvision version : 0.6.0a0+35d732a cuda : 9.2
> 
> The environmental problem has been bothering me for several days and has not been solved yet,if you have same problem,i really hope you can help me.Thank you !

It seems the problem is caused by the version mismatch between  pytorch and cuda (namely pytorch is not compile by this version cuda). One possible solution is download [wheel](https://download.pytorch.org/whl/torch_stable.html). 
If this solution still can't solve the problem, please try torch==1.7.0 and cuda=10.1 using wheel install.

**Comment by Z-Yh-June** [comment]
thank you very much!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-model/MOTR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-model/MOTR] demo with the problem of environment (Issue #22)





  
when i run demo , i meet this problem :
 
(pytracking) ...~/zyh/MOTR$ sh configs/r50_motr_demo.sh Traceback (most recent call last): File "./demo.py", line 28, in from models import build_model File "/home/lx/zyh/MOTR/models/init.py", line 10, in from .deformable_detr import build as build_deformable_detr File "/home/lx/zyh/MOTR/models/deformable_detr.py", line 29, in from .deformable_transformer import build_deforamble_transformer File "/home/lx/zyh/MOTR/models/deformable_transformer.py", line 25, in from models.ops.modules import MSDeformAttn File "/home/lx/zyh/MOTR/models/ops/modules/init.py", line 12, in from .ms_deform_attn import MSDeformAttn File "/home/lx/zyh/MOTR/models/ops/modules/ms_deform_attn.py", line 24, in from ..functions import MSDeformAttnFunction File "/home/lx/zyh/MOTR/models/ops/functions/init.py", line 12, in from .ms_deform_attn_func import MSDeformAttnFunction File "/home/lx/zyh/MOTR/models/ops/functions/ms_deform_attn_func.py", line 21, in import MultiScaleDeformableAttention as MSDA ImportError: /home/lx/anaconda3/envs/pytracking/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa
 
my environment as follow: torch version:1.5.1 torchvision version : 0.6.0a0+35d732a cuda : 9.2
 
The environmental problem has been bothering me for several days and has not been solved yet,if you have same problem,i really hope you can help me.Thank you !
  
It seems the problem is caused by the version mismatch between  pytorch and cuda (namely pytorch is not compile by this version cuda). One possible solution is download wheel.
 If this solution still can't solve the problem, please try torch==1.7.0 and cuda=10.1 using wheel install.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
