### ISSUE TITLE
missing args: local_self_attn

### ISSUE THREAD

**Issue by noahcao** [megvii-model/MOTR#23]
When running the default setting by r50_motr_train.sh for training, there would raise an error as:

![image](https://user-images.githubusercontent.com/17743251/139745556-13610fc3-9996-4c83-849f-d7c0423b5074.png)

This is because of the lack of "local_self_attn" attribute in the main.py argument parser which is later called when building the model.

**Comment by noahcao** [comment]
Also, the argument "new_frame_adaptor" is also missing for the reason.

**Comment by dbofseuofhust** [comment]
> When running the default setting by r50_motr_train.sh for training, there would raise an error as:
> 
> ![image](https://user-images.githubusercontent.com/17743251/139745556-13610fc3-9996-4c83-849f-d7c0423b5074.png)
> 
> This is because of the lack of "local_self_attn" attribute in the main.py argument parser which is later called when building the model.

Training MOTR will not use 'deformable_detr.py' and ‘deformable_transformer.py’, please kind to check if  **--meta_arch motr** is set rightly.
