### ISSUE TITLE
The default model architecture for mot_train?

### ISSUE THREAD

**Issue by noahcao** [megvii-model/MOTR#24]
In the default settings in configs/r50_motr_train.sh, the argument **meta_arch** is not assigned so the model uses 'deformable_detr' in *main.py*.

I just wanted to confirm that if we want to train a MOTR model for training, we should set **--meta_arch motr** in the training script. At the same time, we should rewrite the pretrained model / checkpoint loading code, right?

**Comment by dbofseuofhust** [comment]
> In the default settings in configs/r50_motr_train.sh, the argument **meta_arch** is not assigned so the model uses 'deformable_detr' in _main.py_.
> 
> I just wanted to confirm that if we want to train a MOTR model for training, we should set **--meta_arch motr** in the training script. At the same time, we should rewrite the pretrained model / checkpoint loading code, right?

Thanks for attention!
In fact, the default meta_arch is 'meta_arch ', and there is no need to rewrite the pretrained model / checkpoint loading code when training motr. 
And in the default settings in configs/r50_motr_train.sh, The argument meta_arch is assigned into  **--meta_arch motr** [this line](https://github.com/megvii-model/MOTR/blob/main/configs/r50_motr_train.sh#L15).
