### ISSUE TITLE
About the memory bank

### ISSUE THREAD

**Issue by lyliutwo** [megvii-model/MOTR#27]
Hi!
I found that you use a memory bank in MOTR, but I haven't found its description in the paper. Could you tell me what you use this memory bank for?

**Comment by dbofseuofhust** [comment]
> Hi! I found that you use a memory bank in MOTR, but I haven't found its description in the paper. Could you tell me what you use this memory bank for?

Hi~, the memory bank is set into None in default and our reported results don't use memory bank. Actually, memory bank can boost IDF1 metric, but the training speed and memory cost will increase. So you can set it according to your need.
