### ISSUE TITLE
How and when to enable memory bank

### ISSUE THREAD

**Issue by patchywang** [megvii-model/MOTR#29]
Hello, I find that memory bank would be enabled only if the memory_bank_type argument is passed.

I could not find memory_bank_type is set anywhere in your configs “r50_motr_train.sh” or "r50_motr_eval.sh".

Can you please explain when the memory bank should be enabled? Is it during the train or inference? And what arguments should I pass to make memory bank fully functional?

**Comment by dbofseuofhust** [comment]
> Hello, I find that memory bank would be enabled only if the memory_bank_type argument is passed.
> 
> I could not find memory_bank_type is set anywhere in your configs “r50_motr_train.sh” or "r50_motr_eval.sh".
> 
> Can you please explain when the memory bank should be enabled? Is it during the train or inference? And what arguments should I pass to make memory bank fully functional?

Hi~, the memory bank is set into None in default and our reported results don't use memory bank. Actually, memory bank can boost IDF1 metric, but the training speed and memory cost will increase. So you can set it according to your need just by adding `--memory_bank_type 'memory_bank'` in "r50_motr_train.sh"

**Comment by patchywang** [comment]
Thanks for your quick reply!
