### ISSUE TITLE
Reproduced results on validation set MOT15 with the provided weights(motr_final_0915.pth), MOTA: 29.1% IDF1: 67.1%.

### ISSUE THREAD

**Issue by xiaocc612** [megvii-model/MOTR#32]
Thank you for your wondful work. I run the eval experiment on the MOT15 training set, the result as follows:
 KITTI-13       55.0% 43.8% 73.7% 74.2% 44.1%  42  23 18   1   874  240   2    4 -20.1% 0.189   0   2   0
PETS09-S2L1    79.5% 79.2% 79.9% 93.3% 92.4%  19  17  2   0   355  313   7   54  85.5% 0.263   1   6   0
TUD-Stadtmitte 75.0% 71.4% 79.1% 88.0% 79.4%  10   8  2   0   264  139   8   10  64.4% 0.294   3   6   1
ADL-Rundle-8   66.1% 50.7% 94.9% 95.1% 50.8%  28  26  2   0  6250  330  12   88   2.8% 0.223   4   3   2
KITTI-17       53.2% 42.4% 71.5% 81.7% 48.5%   9   7  2   0   679  143  12   18  -6.6% 0.212   4   9   1
ETH-Pedcross2  86.3% 88.6% 84.1% 86.0% 90.6% 151 105 14  32   606  947  15   47  76.8% 0.163  12   9   8
ETH-Sunnyday   83.0% 75.3% 92.6% 93.8% 76.2%  30  25  3   2   557  118   3   13  64.3% 0.148   1   3   1
TUD-Campus     72.0% 62.1% 85.5% 98.1% 71.3%   8   8  0   0   142    7   4    5  57.4% 0.286   2   2   0
Venice-2       51.2% 35.6% 91.0% 98.4% 38.5%  26  26  0   0 11239  114   8   11 -59.1% 0.231   1   7   1
OVERALL        67.1% 56.3% 83.0% 88.4% 60.0% 570 376 88 106 25451 5017 101  410  29.1% 0.203  75  64  53
Is the something wrong?

On the MOT16 training set:
          IDF1   IDP   IDR  Rcll  Prcn  GT  MT PT ML   FP   FN IDs   FM  MOTA  MOTP IDt IDa IDm
MOT16-02 80.6% 80.1% 81.1% 95.5% 94.3%  54  48  6  0 1035  807  43   82 89.4% 0.097  28  17   2
MOT16-04 90.1% 90.4% 89.8% 89.8% 90.4%  83  58 16  9 4533 4862   0   28 80.2% 0.091   0   0   0
MOT16-05 93.3% 93.6% 93.0% 93.8% 94.3% 125 107 16  2  384  424  10   33 88.0% 0.140   5   7   2
MOT16-09 92.9% 92.8% 93.0% 96.6% 96.4%  25  23  2  0  187  177   3    8 93.0% 0.096   1   2   0
MOT16-10 92.0% 90.6% 93.4% 95.9% 93.0%  54  51  3  0  888  504  24   98 88.5% 0.154  14   4   1
MOT16-11 96.2% 95.0% 97.4% 97.4% 95.0%  69  67  2  0  466  236   0   11 92.3% 0.083   0   0   0
MOT16-13 95.3% 95.9% 94.6% 96.3% 97.7% 107  95  9  3  264  425   7   33 93.9% 0.127   4   6   3
OVERALL  90.1% 90.0% 90.3% 93.3% 93.0% 517 449 54 14 7757 7435  87  293 86.2% 0.106  52  36   8

On the MOT17 training set:
                IDF1   IDP   IDR  Rcll  Prcn   GT  MT    PT ML   FP   FN IDs   FM  MOTA  MOTP IDt IDa IDm
MOT17-10-SDP   94.3% 94.8% 93.8% 96.9% 98.0%   57   55   1  1   257   394  20   73 94.8% 0.150  12   5   2
MOT17-04-SDP   90.1% 90.4% 89.8% 89.8% 90.4%   83   58  16  9  4533  4862   0   28 80.2% 0.091   0   0   0
MOT17-02-DPM   82.0% 83.2% 80.8% 95.7% 98.4%   62   53   6  3   281   801  42   95 94.0% 0.097  27  16   1
MOT17-13-DPM   96.0% 97.5% 94.6% 96.2% 99.3%  110   97   9  4    84   437   7   30 95.5% 0.127   4   6   3
MOT17-13-FRCNN 96.0% 97.5% 94.6% 96.2% 99.3%  110   97   9  4    84   437   7   30 95.5% 0.127   4   6   3
MOT17-11-FRCNN 97.8% 98.0% 97.6% 97.6% 98.0%   75   71   2  2   190   222   0    8 95.6% 0.082   0   0   0
MOT17-11-DPM   97.8% 98.0% 97.6% 97.6% 98.0%   75   71   2  2   190   222   0    8 95.6% 0.082   0   0   0
MOT17-05-DPM   94.5% 95.4% 93.5% 94.0% 95.9%  133  118  14  1   277   414   9   30 89.9% 0.137   4   6   1
MOT17-04-DPM   90.1% 90.4% 89.8% 89.8% 90.4%   83   58  16  9  4533  4862   0   28 80.2% 0.091   0   0   0
MOT17-10-DPM   94.3% 94.8% 93.8% 96.9% 98.0%   57   55   1  1   257   394  20   73 94.8% 0.150  12   5   2
MOT17-04-FRCNN 90.1% 90.4% 89.8% 89.8% 90.4%   83   58  16  9  4533  4862   0   28 80.2% 0.091   0   0   0
MOT17-09-DPM   93.3% 93.8% 92.8% 96.4% 97.4%   26   24   2  0   135   193   3    8 93.8% 0.095   1   2   0
MOT17-02-FRCNN 82.0% 83.2% 80.8% 95.7% 98.4%   62   53   6  3   281   801  42   95 94.0% 0.097  27  16   1
MOT17-09-SDP   93.3% 93.8% 92.8% 96.4% 97.4%   26   24   2  0   135   193   3    8 93.8% 0.095   1   2   0
MOT17-05-FRCNN 94.5% 95.4% 93.5% 94.0% 95.9%  133  118  14  1   277   414   9   30 89.9% 0.137   4   6   1

**Comment by wenjie710** [comment]
Hi, have you solved this problem? I got the same results with reproduced model.

**Comment by xiaocc612** [comment]
> Hi, have you solved this problem? I got the same results with reproduced model.

I did not solve this problem. I think the generalization of the model is not as good as stated in the paper and does not reach the results of the paper's ablation experiment.

**Comment by wenjie710** [comment]
Thanks a lot. By the way, did you try training on MOT17+crowdhuman and testing on MOT17?  Will this reproduce the results of the paper's comparison with SOTA experiment?

**Comment by xiaocc612** [comment]
> Thanks a lot. By the way, did you try training on MOT17+crowdhuman and testing on MOT17? Will this reproduce the results of the paper's comparison with SOTA experiment?

  No, I didn't.
  I tried this: train model on crowdhuman val + MOT17 half (The first part of each video sequence) for 131 epochs (thanks to GPU memory limitation).  The results of the evaluation on the remaining second part of MOT17 are as follows：
                                     IDF1   IDP   IDR  Rcll  Prcn  GT  MT  PT ML   FP    FN IDs   FM  MOTA  MOTP IDt IDa IDm
MOT17-10-FRCNN 60.7% 68.1% 54.7% 69.0% 85.8%  36  15  15  6  678  1845  71  140 56.4% 0.219  15  56   3
MOT17-09-FRCNN 71.5% 75.4% 68.1% 81.4% 90.1%  22  15   7  0  258   537  19   32 71.9% 0.165   7  15   3
MOT17-13-FRCNN 72.9% 78.4% 68.2% 75.4% 86.7%  44  23  15  6  368   782  18   73 63.2% 0.211   7  13   2
MOT17-11-FRCNN 62.2% 66.5% 58.4% 75.7% 86.3%  44  19  10 15  544  1099  22   29 63.2% 0.128   3  20   1
MOT17-04-FRCNN 71.4% 71.9% 71.0% 78.8% 79.9%  69  36  23 10 4817  5126  34   97 58.8% 0.174   3  31   1
MOT17-02-FRCNN 40.2% 46.9% 35.2% 60.7% 80.8%  53  14  31  8 1425  3898 146  207 44.8% 0.196  59  90   5
MOT17-05-FRCNN 65.3% 71.0% 60.4% 73.3% 86.3%  71  29  31 11  392   897  30   45 60.8% 0.201  15  24   9
OVERALL        64.0% 67.7% 60.6% 73.8% 82.5% 339 151 132 56 8482 14184 340  623 57.4% 0.182 109 249  24

**Comment by zyayoung** [comment]
Thank you so much for your interest in our work!

For GPU memory limitation, we now support training with 11GB memory or less by adding `--use_checkpoint` argument. 
To save more GPU memory, we may replace `len(frames) - 2` with `len(frames) - 1` in the following line:
https://github.com/megvii-model/MOTR/blob/4bc797f17e966b49483ad02b454258debf92514d/models/motr.py#L614

The updated code should have MOTA 71-72 on the MOT17 test set. The test result is [here](https://motchallenge.net/method/MOT=5101&chl=10).

We no longer maintain MOT15 validation results. We are exploring MOT17 val_half and DanceTrack as alternatives.
We recommend testing our final result on the MOT17 test set for stability.

**Comment by xiaocc612** [comment]
> Thank you so much for your interest in our work!
> 
> For GPU memory limitation, we now support training with 11GB memory or less by adding `--use_checkpoint` argument. To save more GPU memory, we may replace `len(frames) - 2` with `len(frames) - 1` in the following line:
> 
> https://github.com/megvii-model/MOTR/blob/4bc797f17e966b49483ad02b454258debf92514d/models/motr.py#L614
> 
> The updated code should have MOTA 71-72 on the MOT17 test set. The test result is [here](https://motchallenge.net/method/MOT=5101&chl=10).
> 
> We no longer maintain MOT15 validation results. We are exploring MOT17 val_half and DanceTrack as alternatives. We recommend testing our final result on the MOT17 test set for stability.

Thanks for your reply! 
How does the model perform when trained with shorter video clips? Also, will your paper on arxive.org be updated? Looking forward to it!

**Comment by ZhangSongxi** [comment]
Hi! Can you tell me how to train this model on crowdhuman val + MOT17 half together? I want to know which way can we combine these two datasets into the model. Thanks!

**Comment by Wincioor11** [comment]
> Thanks a lot. By the way, did you try training on MOT17+crowdhuman and testing on MOT17? Will this reproduce the results of the paper's comparison with SOTA experiment?

Hello, I have a similar issue with the pretrained motr model. 

I downloaded the weights from [model](https://drive.google.com/file/d/1K9AbtzTCBNsOD8LYA1k16kf4X0uJi8PC/view?usp=sharing) and ran the 
`sh configs/r50_motr_eval.sh` 
command so the script evaluated the model on MOT15 dataset with the following results 
```
IDF1   IDP   IDR  Rcll  Prcn  GT  MT PT  ML    FP   FN IDs   FM   MOTA  MOTP IDt IDa IDm
ADL-Rundle-6   88.0% 84.1% 92.2% 96.9% 88.5%  24  23  1   0   632  154   6    9  84.2% 0.154   5   3   2
ETH-Bahnhof    56.7% 54.5% 59.2% 66.4% 61.1% 223 104 47  72  3240 2576  27  155  23.8% 0.184  47  14  38
KITTI-13       51.1% 39.6% 72.3% 73.4% 40.1%  42  23 19   0  1017  247   4    6 -36.5% 0.191   3   3   2
PETS09-S2L1    77.3% 76.7% 77.9% 93.9% 92.5%  19  17  2   0   356  283   4   52  86.2% 0.268   3   2   1
TUD-Stadtmitte 79.2% 75.5% 83.3% 92.0% 83.4%  10  10  0   0   212   93   6    7  73.1% 0.289   2   4   1
ADL-Rundle-8   65.1% 49.8% 93.9% 94.2% 50.0%  28  25  3   0  6387  395   8   97  -0.1% 0.226   4   3   2
KITTI-17       50.4% 39.3% 70.3% 78.4% 43.8%   9   6  3   0   786  169  13   21 -23.8% 0.215   5   7   1
ETH-Pedcross2  86.3% 88.0% 84.7% 86.4% 89.8% 151 108 12  31   664  920  12   34  76.4% 0.163  10   6   6
ETH-Sunnyday   78.1% 68.8% 90.3% 92.2% 70.2%  30  25  3   2   745  149   5   17  52.7% 0.160   1   4   1
TUD-Campus     66.0% 53.3% 86.6% 96.7% 59.4%   8   8  0   0   237   12   6    6  29.0% 0.280   4   2   1
Venice-2       54.5% 37.7% 98.3% 98.4% 37.8%  26  25  1   0 11572  111   1    8 -63.6% 0.231   0   1   0
OVERALL        67.5% 56.5% 83.7% 88.2% 59.5% 570 374 91 105 25848 5109  92  412  28.0% 0.206  84  49  55
```

I organized the datasets just like in FairMOT and don't know what is the issue here.

**Comment by zzzzyq-18** [comment]
> 感谢您的精彩工作。我在MOT15训练集上进行eval实验，结果如下： KITTI-13 55.0% 43.8% 73.7% 74.2% 44.1% 42 23 18 1 874 240 2 4 -20.1% 0.189 0 2 0 PETS09-S2L1 79.5% 79.2 A% 79.9% 93.3% 92.4% 19 17 2 0 355 313 7 54 85.5% 0.263 1 6 0 TUD-Stadtmitte 75.0% 71.4% 79.1% 88.0% 79.4% 10 8 2 0 264 139 029 8 10 36.1% 64.1 % Rundle-8 66.1% 50.7% 94.9% 95.1% 50.8% 28 26 2 0 6250 330 12 88 2.8% 0.223 4 3 2 KITTI-17 53.2% 42.4% 71.5% 81.7% 48.5% 9 7 2 0 - 679 8 7 2 0 - 679 1 % 0.212 4 9 1 ETH-Pedcross2 86.3% 88.6% 84.1% 86.0% 90.6% 151 105 14 32 606 947 15 47 76.8% 0.163 12 9 8 ETH-Sunnyday 83.0% 75.3% 92.6% 93.8% 76.2% 30 25 3 2 557 118 3 13 64.3% 0.148 1 3 1 TUD-Campus 72.0% 62.1% 85.5% 98.1% 71.3% 8 4 55 0.4%2 7 0.286 2 2 0 Venice-2 51.2% 35.6% 91.0% 98.4% 38.5% 26 26 0 0 11239 114 8 11 -59.1% 0.231 1 7 1 OVERALL 67.1% 56.3% 83.0% 88.4% 60.0% 570 376 88 106 25451 5017 101 410 29.1% 0.203 75 64 53 有什么问题吗？
> 
> 在 MOT16 训练集上： IDF1 IDP IDR Rcll Prcn GT MT PT ML FP FN IDs FM MOTA MOTP IDt IDa IDm MOT16-02 80.6% 80.1% 81.1% 95.5% 94.3% 54 48 6 0 1035 807 43 82 89.4% 0.097 28 1 2 MOT16-04 90.1% 90.4% 89.8% 89.8% 90.4% 83 58 16 9 4533 4862 0 28 80.2% 0.091 0 0 0 MOT16-05 93.3% 93.6% 93.0% 93.8% 94.3% 125 107 16 2 384 424 10 33 88.0 % 0.140 5 7 2 MOT16-09 92.9% 92.8% 93.0% 96.6% 96.4% 25 23 2 0 187 177 3 8 93.0% 0.096 1 2 0 MOT16-10 92.0% 90.6% 93.4% 8 545% 30.0% 8 545% 504 24 98 88.5% 0.154 14 4 1 MOT16-11 96.2% 95.0% 97.4% 97.4% 95.0% 69 67 2 0 466 236 0 11 92.3% 0.083 0 0 0 MOT16-13 95.3% 95.9% 94.6% 96.3% 97.7% 107 95 9 3 264 425 7 33 93.9% 0.127 4 6 3 OVERALL 90.1% 90.0% 90.3% 93.3% 93.0% 517 449 54 14 7757 7435 87 293 86.2% 0.106 52 36 8
> 
> 在 MOT17 训练集上： IDF1 IDP IDR Rcll Prcn GT MT PT ML FP FN IDs FM MOTA MOTP IDt IDa IDm MOT17-10-SDP 94.3% 94.8% 93.8% 96.9% 98.0% 57 55 1 1 257 394 20 73 94.8% 0.150 12 5 2 MOT17-04-SDP 90.1% 90.4% 89.8% 89.8% 90.4% 83 58 16 9 4533 4862 0 28 80.2% 0.091 0 0 0 MOT17-02-DPM 82.0% 83.2% 80.8% 95.7% 6 8.4% 6 3 281 801 42 95 94.0% 0.097 27 16 1 MOT17-13-DPM 96.0% 97.5% 94.6% 96.2% 99.3% 110 97 9 4 84 437 7 30 95.5% 0.127 4 6 9660% 960% % 96.2% 99.3% 110 97 9 4 84 437 7 30 95.5% 0.127 4 6 3 MOT17-11-FRCNN 97.8% 98.0% 97.6% 97.6% 98.0% 75 71 2 2 190 222 0 8 95.6% 0.082 0 0 0 MOT17-11-DPM 97.8% 98.0% 97.6% 97.6% 98.0% 290 75 221 21 0 8 95.6% 0.082 0 0 0 MOT17-05-DPM 94.5% 95.4% 93.5% 94.0% 95.9% 133 118 14 1 277 414 9 30 89.9% 0.137 4 6 1 MOT17-04-DPM 90.1% 90.4% 89.1% 90..8% 90.4% 83 58 16 9 4533 4862 0 28 80.2% 0.091 0 0 0 MOT17-10-DPM 94.3% 94.8% 93.8% 96.9% 98.0% 57 55 1 1 257 394 20 73 94.8% 0.1500 1-2FR52 CNN 90.1% 90.4% 89.8% 89.8% 90.4% 83 58 16 9 4533 4862 0 28 80.2% 0.091 0 0 0 MOT17-09-DPM 93.3% 93.8% 92.8% 96.4% 97.4% 26 903 2 9 59.3 8% 903 24 9 59.3 1 2 0 MOT17-02-FRCNN 82.0% 83.2% 80.8% 95.7% 98.4% 62 53 6 3 281 801 42 95 94.0% 0.097 27 16 1 MOT17-09-SDP 93.3% 93.8% 92.8% 96.34% 97.4% 56 29 3 8 93.8% 0.095 1 2 0 MOT17-05-FRCNN 94.5% 95.4% 93.5% 94.0% 95.9% 133 118 14 1 277 414 9 30 89.9% 0.137 4 6 1

Are these results obtained by submitting to the MOT platform instead of running the code of this project?

**Comment by wuzhiqi111** [comment]
> Thank you for your wondful work. I run the eval experiment on the MOT15 training set, the result as follows: KITTI-13 55.0% 43.8% 73.7% 74.2% 44.1% 42 23 18 1 874 240 2 4 -20.1% 0.189 0 2 0 PETS09-S2L1 79.5% 79.2% 79.9% 93.3% 92.4% 19 17 2 0 355 313 7 54 85.5% 0.263 1 6 0 TUD-Stadtmitte 75.0% 71.4% 79.1% 88.0% 79.4% 10 8 2 0 264 139 8 10 64.4% 0.294 3 6 1 ADL-Rundle-8 66.1% 50.7% 94.9% 95.1% 50.8% 28 26 2 0 6250 330 12 88 2.8% 0.223 4 3 2 KITTI-17 53.2% 42.4% 71.5% 81.7% 48.5% 9 7 2 0 679 143 12 18 -6.6% 0.212 4 9 1 ETH-Pedcross2 86.3% 88.6% 84.1% 86.0% 90.6% 151 105 14 32 606 947 15 47 76.8% 0.163 12 9 8 ETH-Sunnyday 83.0% 75.3% 92.6% 93.8% 76.2% 30 25 3 2 557 118 3 13 64.3% 0.148 1 3 1 TUD-Campus 72.0% 62.1% 85.5% 98.1% 71.3% 8 8 0 0 142 7 4 5 57.4% 0.286 2 2 0 Venice-2 51.2% 35.6% 91.0% 98.4% 38.5% 26 26 0 0 11239 114 8 11 -59.1% 0.231 1 7 1 OVERALL 67.1% 56.3% 83.0% 88.4% 60.0% 570 376 88 106 25451 5017 101 410 29.1% 0.203 75 64 53 Is the something wrong?
> 
> On the MOT16 training set: IDF1 IDP IDR Rcll Prcn GT MT PT ML FP FN IDs FM MOTA MOTP IDt IDa IDm MOT16-02 80.6% 80.1% 81.1% 95.5% 94.3% 54 48 6 0 1035 807 43 82 89.4% 0.097 28 17 2 MOT16-04 90.1% 90.4% 89.8% 89.8% 90.4% 83 58 16 9 4533 4862 0 28 80.2% 0.091 0 0 0 MOT16-05 93.3% 93.6% 93.0% 93.8% 94.3% 125 107 16 2 384 424 10 33 88.0% 0.140 5 7 2 MOT16-09 92.9% 92.8% 93.0% 96.6% 96.4% 25 23 2 0 187 177 3 8 93.0% 0.096 1 2 0 MOT16-10 92.0% 90.6% 93.4% 95.9% 93.0% 54 51 3 0 888 504 24 98 88.5% 0.154 14 4 1 MOT16-11 96.2% 95.0% 97.4% 97.4% 95.0% 69 67 2 0 466 236 0 11 92.3% 0.083 0 0 0 MOT16-13 95.3% 95.9% 94.6% 96.3% 97.7% 107 95 9 3 264 425 7 33 93.9% 0.127 4 6 3 OVERALL 90.1% 90.0% 90.3% 93.3% 93.0% 517 449 54 14 7757 7435 87 293 86.2% 0.106 52 36 8
> 
> On the MOT17 training set: IDF1 IDP IDR Rcll Prcn GT MT PT ML FP FN IDs FM MOTA MOTP IDt IDa IDm MOT17-10-SDP 94.3% 94.8% 93.8% 96.9% 98.0% 57 55 1 1 257 394 20 73 94.8% 0.150 12 5 2 MOT17-04-SDP 90.1% 90.4% 89.8% 89.8% 90.4% 83 58 16 9 4533 4862 0 28 80.2% 0.091 0 0 0 MOT17-02-DPM 82.0% 83.2% 80.8% 95.7% 98.4% 62 53 6 3 281 801 42 95 94.0% 0.097 27 16 1 MOT17-13-DPM 96.0% 97.5% 94.6% 96.2% 99.3% 110 97 9 4 84 437 7 30 95.5% 0.127 4 6 3 MOT17-13-FRCNN 96.0% 97.5% 94.6% 96.2% 99.3% 110 97 9 4 84 437 7 30 95.5% 0.127 4 6 3 MOT17-11-FRCNN 97.8% 98.0% 97.6% 97.6% 98.0% 75 71 2 2 190 222 0 8 95.6% 0.082 0 0 0 MOT17-11-DPM 97.8% 98.0% 97.6% 97.6% 98.0% 75 71 2 2 190 222 0 8 95.6% 0.082 0 0 0 MOT17-05-DPM 94.5% 95.4% 93.5% 94.0% 95.9% 133 118 14 1 277 414 9 30 89.9% 0.137 4 6 1 MOT17-04-DPM 90.1% 90.4% 89.8% 89.8% 90.4% 83 58 16 9 4533 4862 0 28 80.2% 0.091 0 0 0 MOT17-10-DPM 94.3% 94.8% 93.8% 96.9% 98.0% 57 55 1 1 257 394 20 73 94.8% 0.150 12 5 2 MOT17-04-FRCNN 90.1% 90.4% 89.8% 89.8% 90.4% 83 58 16 9 4533 4862 0 28 80.2% 0.091 0 0 0 MOT17-09-DPM 93.3% 93.8% 92.8% 96.4% 97.4% 26 24 2 0 135 193 3 8 93.8% 0.095 1 2 0 MOT17-02-FRCNN 82.0% 83.2% 80.8% 95.7% 98.4% 62 53 6 3 281 801 42 95 94.0% 0.097 27 16 1 MOT17-09-SDP 93.3% 93.8% 92.8% 96.4% 97.4% 26 24 2 0 135 193 3 8 93.8% 0.095 1 2 0 MOT17-05-FRCNN 94.5% 95.4% 93.5% 94.0% 95.9% 133 118 14 1 277 414 9 30 89.9% 0.137 4 6 1

你好，请问下mot17的evaluation结果是怎么得出的，也是运行eval.py吗
