### ISSUE TITLE
full evaluation results on  MOT17.

### ISSUE THREAD

**Issue by noahcao** [megvii-model/MOTR#34]
Thanks for the great work.

Looks like I can't find MOTR's results on the MOT17 leaderboard. Could you please provide the full evaluation results, including such as HOTA, AssA, Frag and so on, to provide more sense of its performance?

Moreover, have you tried MOTR on MOT20 as well?

**Comment by vaesl** [comment]
> 

Thanks for your interest on MOTR!

As for your question, we have released the MOTR results on the MOT17 leaderboard. Please kindly refer to https://motchallenge.net/method/MOT=5101&chl=10 for more details. Up to now, we have not tried MOTR on MOT20 dataset. Feel free to have a try.

**Comment by noahcao** [comment]
Thank you so much for the provided update!
