### ISSUE TITLE
Adaptation to DanceTrack

### ISSUE THREAD

**Issue by noahcao** [megvii-model/MOTR#36]
Hi,

Thanks for the wonderful work.

May I ask, compared to the implementation on MOT17 dataset, what adaptation you made for DanceTrack? I noticed the change of image resolution during training, etc. Just in case I miss anything. Thank you.

**Comment by zyayoung** [comment]
The only change was data source (MOT17 -> DanceTrack) and crop resolution.
The new crop resolution was adopted from [TransTrack](https://github.com/PeizeSun/TransTrack) but we observed no significant difference in performance.

We welcome your reply if you have any further questions.

**Comment by noahcao** [comment]
Thank you for the reply!
