### ISSUE TITLE
why the parameter 'tensor_list' i transform to the function 'nested_tensor_from_tensor_list' is a dict.

### ISSUE THREAD

**Issue by quxu91** [megvii-model/MOTR#37]
the error just like this
![image](https://user-images.githubusercontent.com/49909166/162751301-5eafa656-2072-4482-8df3-3a2bb44b303d.png)

**Comment by quxu91** [comment]
the error just like this 
![image](https://user-images.githubusercontent.com/49909166/162750970-21f1639f-c4b7-4456-b70c-caa586e08c37.png)

**Comment by nwoyecid** [comment]
What is the solution to this issue?

**Comment by nwoyecid** [comment]
If you have similar issue, check that you are passing the correct num_classes in your dataset to your model.
