### ISSUE TITLE
How to train on the DanceTrack?

### ISSUE THREAD

**Issue by quxu91** [megvii-model/MOTR#38]
Hi, thanks for your great job!  I try to train on the DanceTrack,but i cannot found the dancetrack.train.how can i generate this file

**Comment by zyayoung** [comment]
Thank you for your interest in our work!
The DanceTrack dataset adapter [dance.py](https://github.com/megvii-model/MOTR/blob/main/datasets/dance.py) is updated and **no preprocessing is required**.
Just run `configs/r50_motr_train_dance.sh` and the `--data_txt_path_train` argument is ignored.

Sorry for causing confusion.

**Comment by quxu91** [comment]
> Thank you for your interest in our work! The DanceTrack dataset adapter [dance.py](https://github.com/megvii-model/MOTR/blob/main/datasets/dance.py) is updated and **no preprocessing is required**. Just run `configs/r50_motr_train_dance.sh` and the `--data_txt_path_train` argument is ignored.
> 
> Sorry for causing confusion.

Thanks! 
I get it.
