### ISSUE TITLE
About ablation study

### ISSUE THREAD

**Issue by haiyang426** [megvii-model/MOTR#39]
Hello
For the ablation study in
The impact of increasing video clip **length** in **Collective Average Loss** during training on tracking performance.
Length MOTA↑ IDF1↑ IDS↓
         2      44.9   63.4  257
         3      51.6   59.4  424
         4      50.6   64.0  314
         5      53.2   70.5  155

Can I know if the epoch settings at different lengths are the same as 200epoch or is the length 2 corresponds to 50, 3 is 90, 4 is 120, 5 is 200, a gradual increase like this？
Thanks

**Comment by vaesl** [comment]
It is the same as 200 epochs instead of a gradual increase.
