### ISSUE TITLE
Congratulation!!!

### ISSUE THREAD

**Issue by xiaocc612** [megvii-model/MOTR#42]

**Comment by vaesl** [comment]
Thanks a lot! The MOTR paper is finally accepted by ECCV 2022 after a long submission schedule! The great performance on DanceTrack dataset brings impressive comments from the ECCV reviewers. The contribution of MOTR is acknowledged by the AC of ECCV as well as the researchers working on MOT.

**Comment by xiaocc612** [comment]
> Thanks a lot! The MOTR paper is finally accepted by ECCV 2022 after a long submission schedule! The great performance on DanceTrack dataset brings impressive comments from the ECCV reviewers. The contribution of MOTR is acknowledged by the AC of ECCV as well as the researchers working on MOT.
It's so hard, I've been following this work of yours. I think you guys did a better job and are more in line with Transformer logic than TransTrack and other contemporaries. Congratulations again.
