### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'new_frame_adaptor'

### ISSUE THREAD

**Issue by lizhi139** [megvii-model/MOTR#47]

**Comment by zyayoung** [comment]
Please refer to #23.

**Comment by lizhi139** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lizhi139** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
