### ISSUE TITLE
How to change backbone ?

### ISSUE THREAD

**Issue by CarlHuangNuc** [megvii-model/MOTR#49]
Hi ,

        I want to change Deformable DETR  Backbone from R50 to Swin B??

        Whether code can easy support change backbone ?

**Comment by zyayoung** [comment]
This repo doesn't support Swin backbone yet.
You may refer to [this repo](https://github.com/zyayoung/Iter-Deformable-DETR) which supports Swin-L in a Deformable DETR code base.
