### ISSUE TITLE
evaluation on dancetrack

### ISSUE THREAD

**Issue by iTruffle** [megvii-model/MOTR#55]
Thank you for this great job.
I want to know how i can evaluate the results of dancetrack?
I successfully run this project on dancetrack test, but I can not get the final results like HOTA, MOTA etc.

**Comment by zyayoung** [comment]
You can submit it to the official DanceTrack evaluation website https://competitions.codalab.org/competitions/35786.

**Comment by iTruffle** [comment]
I am so sorry. I have tryed, but failed.
![image](https://user-images.githubusercontent.com/80766557/188615397-467c734a-5613-4978-beb2-0d7c7b2ca6f2.png)

**Comment by zyayoung** [comment]
I guess that is because there is an ongoing DanceTrack competition. You may try https://codalab.lisn.upsaclay.fr/competitions/5832.

**Comment by iTruffle** [comment]
How long will I wait?
![image](https://user-images.githubusercontent.com/80766557/188618220-c58fb27a-8872-4082-9e72-c73effa0d214.png)
When I upload my .zip file, the website show a message,"An unexpected error occurred."

**Comment by iTruffle** [comment]
![image](https://user-images.githubusercontent.com/80766557/188618463-1a6f8d10-d564-4169-a41b-f2fe79037662.png)

**Comment by zyayoung** [comment]
We haven't tried submitting it to the new website yet. It seems to be an issue with the dataset website.

**Comment by iTruffle** [comment]
Where should I submit?

**Comment by iTruffle** [comment]
I submitted the file here just now.
![image](https://user-images.githubusercontent.com/80766557/188619575-3d5e48e4-77f4-4965-b0d7-020ae928c05f.png)

**Comment by iTruffle** [comment]
Do you have wechat? Are you Chinese?
