### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by eeric** [megvii-model/MOTR#6]
run:
sh configs/r50_motr_submit.sh

result:
....
filter init box 442 44
filter init box 443 44
save init track 443 45
save init track 444 44
save init track 449 46
totally 13 boxes are filtered.
totally 4107 dts 0 occlusion dts
......

while not accuracy rate or error.

**Comment by TerranLord** [comment]
We cannot directly evaluate model on MOT17 test set since the annotation of MOT 17 test set is not available for public use.   Thus, only prediction result is generated for further online evaluation if run "submit.sh".

**Comment by eeric** [comment]
oh, thanks!

**Comment by zzzzyq-18** [comment]
> 我们不能直接在 MOT17 测试集上评估模型，因为 MOT 17 测试集的注释不可供公众使用。因此，如果运行“submit.sh”，则只生成预测结果以供进一步在线评估。

Please ask whether the test on the Dancetrack dataset uses the verification set or the test set, if it is a test set, but the Dancetrack data set does not give the label of the test set, where does the evaluation index come from.
