### ISSUE TITLE
If there are both tracking and detection bounding boxes for the same target

### ISSUE THREAD

**Issue by xucheng-920** [megvii-model/MOTR#68]
If there are both tracking and detection bounding boxes for the same target, how should one of them be filtered out.

**Comment by mmm-cc** [comment]
hello, did you solve this problem? I have the same confuse

**Comment by TerranLord** [comment]
> hello, did you solve this problem? I have the same confuse

During training, the tracked targets are excluded from one-to-one matching between detection queries and GT targets. Therefore, detection queries are learned to detect new-born targets and ignore the tracked targets.
